# Generated by Django 6.0.7 on 2026-08-15 07:46

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AccountClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "code",
                    models.IntegerField(
                        db_comment="区分ID",
                        db_default=0,
                        default=0,
                        unique=True,
                        verbose_name="区分ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        db_comment="区分名",
                        db_default="区分名",
                        default="区分名",
                        max_length=100,
                        null=True,
                        verbose_name="区分名",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                        verbose_name="登録日時",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_default=django.db.models.functions.datetime.Now(),
                        verbose_name="更新日時",
                    ),
                ),
            ],
            options={
                "verbose_name": "アカウント区分",
                "db_table": "account_class",
                "db_table_comment": "アカウント区分",
            },
        ),
        migrations.CreateModel(
            name="AccountList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_comment="アカウント名",
                        db_default="アカウント名",
                        default="アカウント名",
                        max_length=100,
                        verbose_name="アカウント名",
                    ),
                ),
                (
                    "class_id",
                    models.IntegerField(
                        db_comment="区分ID", db_default=0, default=0, verbose_name="区分ID"
                    ),
                ),
                (
                    "class_name",
                    models.CharField(
                        db_comment="区分名",
                        db_default="区分名",
                        default="区分名",
                        max_length=100,
                        verbose_name="区分名",
                    ),
                ),
                (
                    "login_url",
                    models.CharField(
                        db_comment="ログインURL",
                        db_default="ログインURL",
                        default="ログインURL",
                        max_length=200,
                        verbose_name="ログインURL",
                    ),
                ),
                (
                    "user_id",
                    models.CharField(
                        db_comment="ユーザID",
                        db_default="ユーザID",
                        default="ユーザID",
                        max_length=20,
                        verbose_name="ユーザID",
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        db_comment="パスワード",
                        db_default="パスワード",
                        default="パスワード",
                        max_length=50,
                        verbose_name="パスワード",
                    ),
                ),
                (
                    "del_flg",
                    models.BooleanField(
                        db_comment="削除フラグ",
                        db_default=False,
                        default=False,
                        verbose_name="削除フラグ",
                    ),
                ),
                (
                    "member_id",
                    models.CharField(
                        blank=True,
                        db_comment="会員ID",
                        max_length=20,
                        null=True,
                        verbose_name="会員ID",
                    ),
                ),
                (
                    "status1",
                    models.CharField(
                        blank=True,
                        db_comment="ステータス1",
                        max_length=10,
                        null=True,
                        verbose_name="ステータス1",
                    ),
                ),
                (
                    "status2",
                    models.CharField(
                        blank=True,
                        db_comment="ステータス2",
                        max_length=10,
                        null=True,
                        verbose_name="ステータス2",
                    ),
                ),
                (
                    "memo",
                    models.TextField(blank=True, db_comment="メモ", null=True, verbose_name="メモ"),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True,
                        db_comment="会社名",
                        max_length=100,
                        null=True,
                        verbose_name="会社名",
                    ),
                ),
                (
                    "company_url",
                    models.CharField(
                        blank=True,
                        db_comment="会社URL",
                        max_length=200,
                        null=True,
                        verbose_name="会社URL",
                    ),
                ),
                (
                    "company_tel",
                    models.CharField(
                        blank=True,
                        db_comment="会社TEL",
                        max_length=20,
                        null=True,
                        verbose_name="会社TEL",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                        verbose_name="登録日時",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_default=django.db.models.functions.datetime.Now(),
                        verbose_name="更新日時",
                    ),
                ),
            ],
            options={
                "verbose_name": "アカウント一覧",
                "db_table": "account_list",
                "db_table_comment": "アカウント一覧",
            },
        ),
    ]
