# Generated by Django 6.0.7 on 2026-08-15 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountclass",
            name="name",
            field=models.CharField(
                blank=True,
                db_comment="区分名",
                db_default="",
                default="",
                max_length=100,
                verbose_name="区分名",
            ),
        ),
        migrations.AlterField(
            model_name="accountlist",
            name="company_name",
            field=models.CharField(
                blank=True,
                db_comment="会社名",
                db_default="",
                default="",
                max_length=100,
                verbose_name="会社名",
            ),
        ),
        migrations.AlterField(
            model_name="accountlist",
            name="company_tel",
            field=models.CharField(
                blank=True,
                db_comment="会社TEL",
                db_default="",
                default="",
                max_length=20,
                verbose_name="会社TEL",
            ),
        ),
        migrations.AlterField(
            model_name="accountlist",
            name="company_url",
            field=models.CharField(
                blank=True,
                db_comment="会社URL",
                db_default="",
                default="",
                max_length=200,
                verbose_name="会社URL",
            ),
        ),
        migrations.AlterField(
            model_name="accountlist",
            name="member_id",
            field=models.CharField(
                blank=True,
                db_comment="会員ID",
                db_default="",
                default="",
                max_length=20,
                verbose_name="会員ID",
            ),
        ),
        migrations.AlterField(
            model_name="accountlist",
            name="memo",
            field=models.TextField(
                blank=True, db_comment="メモ", db_default="", default="", verbose_name="メモ"
            ),
        ),
        migrations.AlterField(
            model_name="accountlist",
            name="status1",
            field=models.CharField(
                blank=True,
                db_comment="ステータス1",
                db_default="",
                default="",
                max_length=10,
                verbose_name="ステータス1",
            ),
        ),
        migrations.AlterField(
            model_name="accountlist",
            name="status2",
            field=models.CharField(
                blank=True,
                db_comment="ステータス2",
                db_default="",
                default="",
                max_length=10,
                verbose_name="ステータス2",
            ),
        ),
    ]
