# Generated by Django 6.0.7 on 2026-08-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_alter_accountclass_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountclass",
            name="name",
            field=models.CharField(
                db_comment="区分名",
                db_default="区分名",
                default="区分名",
                max_length=100,
                verbose_name="区分名",
            ),
        ),
    ]
