# Generated by Django 6.0.7 on 2026-08-15 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0003_alter_accountclass_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountlist",
            name="member_id",
            field=models.CharField(
                blank=True,
                db_comment="会員ID",
                db_default="",
                default="",
                max_length=100,
                verbose_name="会員ID",
            ),
        ),
        migrations.AlterField(
            model_name="accountlist",
            name="password",
            field=models.CharField(
                db_comment="パスワード",
                db_default="パスワード",
                default="パスワード",
                max_length=100,
                verbose_name="パスワード",
            ),
        ),
        migrations.AlterField(
            model_name="accountlist",
            name="status1",
            field=models.CharField(
                blank=True,
                db_comment="ステータス1",
                db_default="",
                default="",
                max_length=50,
                verbose_name="ステータス1",
            ),
        ),
        migrations.AlterField(
            model_name="accountlist",
            name="status2",
            field=models.CharField(
                blank=True,
                db_comment="ステータス2",
                db_default="",
                default="",
                max_length=50,
                verbose_name="ステータス2",
            ),
        ),
        migrations.AlterField(
            model_name="accountlist",
            name="user_id",
            field=models.CharField(
                db_comment="ユーザID",
                db_default="ユーザID",
                default="ユーザID",
                max_length=100,
                verbose_name="ユーザID",
            ),
        ),
    ]
