# Generated by Django 6.0.7 on 2026-08-22 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0004_alter_accountlist_member_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountlist",
            name="sort",
            field=models.IntegerField(db_comment="ソート", db_default=9999, default=9999, verbose_name="ソート"),
        ),
        migrations.AlterField(
            model_name="accountlist",
            name="login_url",
            field=models.CharField(blank=True, db_comment="ログインURL", db_default="ログインURL", default="ログインURL", max_length=500, verbose_name="ログインURL"),
        ),
    ]
